config/routes.rb
Makevention::Application.routes.draw do

  resources :users
  resources :people
  resources :sessions
  resources :organizations
  root to: 'people#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :contact_info
  
  accepts_nested_attributes_for :contact_info

  has_many :event_registrations
  has_many :org_people

  has_many :events, through: :event_registrations
  has_many :people, through: :org_people    
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :signed_in_user

  def new
    @organization = Organization.new
  end

  def create
    @person = current_user.person
    @organization.org_people.build


    @organization = Organization.new(createorganization_params)

    if (Organization.exists?(:username => @organization.name)) #pre-check
      if (@organization.errors == nil)
        @organization.errors = ActiveModel::Errors.new(@organization)
      end
      @organization.errors.add(:username, "The organization name you've chosen is already in use.  Please choose a different organization name.")
    end

    begin
      if @organization.save
        redirect_to edit_organization_url(@organization) 
      else
        render 'new'
      end
    rescue ActiveRecord::RecordNotUnique #insurance
      if (@user.errors == nil)
        @user.errors = ActiveModel::Errors.new(@user)
      end
      @user.errors.add(:username, "The username you've chosen is already in use.  Please choose a different username.")
      render 'new'
    end
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def index
    @organizations = Organizations.all
  end
end

private
def createorganization_params
  params.require(:organization).permit(:id, :name, contact_info_attributes: [:id, :email, :phone, :website, :address_street_1, :address_street_2, :address_city, :address_state, :address_zip ])
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/new.html.erb
<%= form_for :organization, url: organizations_path do |f| %>
    <% if @organization.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@organization.errors.count, "error") %> prevented this record from being saved:</h2>
          <ul>
            <% @organization.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <%= f.fields_for :contact_info do |c| %>
		<%= render "contact_info", :f => c %>
    <% end %>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', people_path %>